version: '2.1'
services:
  api-service:
    image: todolist:v12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "7000:2030"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:alpine3.16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
        - "5432:5432"
  client_service:
    image: tasks:v12
    depends_on:
      - api-service
    environment:
      API_SERVICE_HOST: api-service

    ports:
      - "4000:4000"