version: '2.4.1'
services:
  api_service:
    image: to_do_app:v1
    restart: always
    ports:
      - "2030:2030"
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:12.10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB : tasksdb
    ports:
        - "5432:5432"
